### ISSUE TITLE
The instance scriptTableActor. does not exist

### ISSUE THREAD

**Issue by shkolnik770** [weswilliams/GivWenZen#1]
1. Downloaded givwenzen-1.0.2.zip
2. extracted
3. java -jar ./lib/fitnesse.jar
4. Executed "AddTwoNumbers"
5. Got 24 exceptions. The only one I see is "The instance scriptTableActor. does not exist"

Update: this only happense after running mvn clean install. Without running mvn clean install, everything seems to work find.

**Comment by weswilliams** [comment]
I might remove the pom file from the zip as it is already built to run and mvn clean install works fine from the repo.
