### ISSUE TITLE
Could not create class file from file

### ISSUE THREAD

**Issue by matej2** [weswilliams/GivWenZen#11]
Hello, 

I am working on some tests and when i change fitnesse fixtures, i oftenly get error:

> org.givwenzen.reflections.ReflectionsException: could not create class file from file

From this, i cant know where is the error. How or where can i find more detailed information on what is actually the problem?

**Comment by HristoDimitrov91** [comment]
Can you please give more information on fitnesse versions and project setup and how are you running your tests. When does this error started appearing?

**Comment by matej2** [comment]
Nevermind, I solved the error

**Comment by HristoDimitrov91** [comment]
O, thats, great! Do you mind sharing your solution so others can benefit :)
