### ISSUE TITLE
Is it possible to update the version in Maven?

### ISSUE THREAD

**Issue by eireglas** [weswilliams/GivWenZen#13]
I see there has been a few commits since the version that's in Maven. Is it possible to push that latest version to it as we have it has a maven dependency?

**Comment by weswilliams** [comment]
I did update libraries for someone recently to sort latest fitnesse. However, I don't recall that I had deployed this to a maven repo. Is it on maven central? If it is, I'm sure I don't own that to be able to update it.

**Comment by eireglas** [comment]
Thanks for coming back to me. Here is where I've seen it in Maven: https://mvnrepository.com/artifact/com.github.bernerbits/givwenzen
I can't really see who might've put this up here...it'd be good to get it updated :)

**Comment by weswilliams** [comment]
I'm sorry, I'm not the owner and nor do I know who is. What I did in the past was create my own repo format in version control and add a custom repo. I think the pom file shows that but to the old googlecode repo.
