### ISSUE TITLE
GivWenZen tries to access a deprecated google method that's been deleted

### ISSUE THREAD

**Issue by AndrewTownsend** [weswilliams/GivWenZen#3]
I can't tell for sure, but it looks like GivWenZen has the same issue that these folks did: https://issues.apache.org/jira/browse/CASSANDRA-6007 

It seems that Google deprecated the MapMaker.makeComputingMap method some time back and finally deleted it.  This exception now gets thrown:

java.lang.IllegalAccessError: tried to access method com.google.con.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class org.givwenzen.reflections.Store

If it's the same issue, please update the code to use the CacheLoader instead (https://code.google.com/p/guava-libraries/wiki/MapMakerMigration)

**Comment by weswilliams** [comment]
This is actually a significant rewrite of loading step classes dynamically. I am looking for a better way to handle this before doing that.

**Comment by weswilliams** [comment]
Checked in a fix to this and will be in the next release

**Comment by AndrewTownsend** [comment]
I actually ended up forking the codebase and tweaking it.  Not sure if I did it in a standard way though.
