### ISSUE TITLE
GivWenZen doesn't parse some data types with the latest version of FitNesse

### ISSUE THREAD

**Issue by veskoy** [weswilliams/GivWenZen#7]
Greetings!

Upgrading FitNesse from a 2014 version to latest resulted in some compatibility issues with GivWenZen. Many tests started to fail and a quick debugging session showed that all affected scenarios incorporate the [Hash Table markup syntax](http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupHashTable). The hash table is correctly matched by the regular expression, however it is passed as a String to the @DomainStep method which is expecting a Map.

Example scenario:
```
|given|a person with data !{first_name: "Bob", last_name: "Martin"}|
...
```

```java
@DomainStep("a person with data (.*)")
public void createPersonWithData(Map<String, String> data) {
    // do something
}
```

Side by side debugging of the old and new versions showed that after the update **PropertyEditorParser#canParse** starts to return **false** for the Hash Table. Further research showed that there wasn't a proper editor registered for the data type.

I found that there was a **MapEditor** class in the **fitnesse.slim.converters** package of the older version I was using. The MapEditor class was replaced at some point in time with [MapConverter](https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/slim/converters/MapConverter.java) class.

I also spotted the [ConverterRegistry](https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/slim/converters/ConverterRegistry.java) class. Then I did a few tweaks to PropertyEditorParser class:

```java
    public static Converter getPropertyConverterFor(Class<?> paramerterType) {
        return ConverterRegistry.getConverterForClass(paramerterType);
    }

    public boolean canParse(Class<?> paramerterType) {
        return getPropertyConverterFor(paramerterType) != null;
    }

    public Object parse(Object paramerter, Class<?> paramerterType) throws Exception {
        Converter propertyConverter = getPropertyConverterFor(paramerterType);
        return propertyConverter.fromString(paramerter.toString());
    }
```

And tests started passing - the hash table syntax was successfully parsed and passed as a Map to the @DomainStep method.

I can open a PR if you find the proposed solution reasonable.

Cheers! :beers:

**Comment by weswilliams** [comment]
Please open the PR
